server:
  port: 19000
spring:
  application:
    name: zuul-gateway
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:19200/eureka/,http://admin:123456@localhost:19201/eureka/
zuul:
  # 路由
  prefix: /api # 路由前缀
  ignored-services: stock-service # 服务名称排除，多个服务逗号分隔，* 排除所有
  routes:
    order-service: # 路由 id 自定义
      path: /order/** # 配置网关路径
      serviceId: order-service # 配置映射服务
  # 限流
  ratelimit:
    enabled: true
    repository: REDIS # 储存方式
    policy-list:
      order-service:
        - limit: 5
          refresh-interval: 60 # 限制 60s 内允许访问 5 次
          type:
            - user # 应用于用户
            - origin # 应用于源IP
            - url # 应用于URL
management:
  endpoints:
    web:
      exposure:
        # hystrix-dashboard 访问接口
        include: hystrix.stream
