server:
  port: 18080
spring:
  application:
    name: zuul-gateway
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:19200/eureka/,http://admin:123456@localhost:19201/eureka/
zuul:
  # 路由
  prefix: /api # 路由前缀
  ignored-services: comment-service # 服务名称排除，多个服务逗号分隔，* 排除所有
  routes:
    order-service: # 路由 id 自定义
      path: /order-service/** # 配置网关路径
      serviceId: order-service # 配置映射服务
    detail-service: # 路由 id 自定义
      path: /detail-service/** # 配置网关路径
      serviceId: detail-service # 配置映射服务
management:
  endpoints:
    web:
      exposure:
        # hystrix-dashboard 访问接口
        include: hystrix.stream
